### ISSUE TITLE
Check the accuracy of the transformation

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/recexcavAAR#5] opened 2017-07-28 17:16 UTC

**Comment by MoritzMennenga** [comment] 2017-08-10 13:02
I compared a rectified image from qgis with the drawing from ACAD. They fit perfect. In the end we need maybe some kind of objective classification.

There seems to be a problem:
If the profile is nearly N-S orientated (I used original field data), the part

```
    #y coordinates of the profile  

    yw <- c(coord_proc$y)

    #x coordinates of the profile

    xw <- c(coord_proc$x)

    fm <- lm(yw ~ xw)
```

can't calculate a slope in the regression. Has anyone an idea?


Here is the excample data:

> COORY | COORX | COORZ | Att2 | Att4
> 6060136.45 | 465421.58 | 2.998 | 32 | E
> 6060136.47 | 465421.565 | 3.3 | 32 | E
> 6060135.89 | 465421.556 | 3.176 | 32 | E
> 6060135.03 | 465421.548 | 2.986 | 32 | E
> 6060135.06 | 465421.514 | 3.359 | 32 | E

```
coord_proc <- tibble::tribble(
  ~y , ~x , ~COORZ , ~Att2 , ~Att4,
  6060136.45 , 465421.58 , 2.998 , 32 , "E",
  6060136.47 , 465421.565 , 3.3 , 32 , "E",
  6060135.89 , 465421.556 , 3.176 , 32 , "E",
  6060135.03 , 465421.548 , 2.986 , 32 , "E",
  6060135.06 , 465421.514 , 3.359 , 32 , "E"
)
```

**Comment by nevrome** [comment] 2017-08-11 08:58
OK Moritz, we discussed about this in the ISAAK meeting yesterday.

There are multiple possible reasons why `lm()` produces no slope value. Discussions about this can be found [here](https://stats.stackexchange.com/questions/25804/why-would-r-return-na-as-a-lm-coefficient) or [here](https://stackoverflow.com/questions/7337761/linear-regression-na-estimate-just-for-last-coefficient). In the case of your example data it seems to be a problem of the scale relation of the two input variables. @dakni can explain this better, I guess. 

If you rescale the data by moving it closer to the zero point, you avoid this problem.

```
coord_proc <- tibble::tribble(
  ~y , ~x , ~COORZ , ~Att2 , ~Att4,
  6060136.45 , 465421.58 , 2.998 , 32 , "E",
  6060136.47 , 465421.565 , 3.3 , 32 , "E",
  6060135.89 , 465421.556 , 3.176 , 32 , "E",
  6060135.03 , 465421.548 , 2.986 , 32 , "E",
  6060135.06 , 465421.514 , 3.359 , 32 , "E"
)

yw <- c(coord_proc$y) - min(coord_proc$y)
xw <- c(coord_proc$x) - min(coord_proc$x)

lm(yw ~ xw)
```

To look a bit beyond your initial question, the same problem will also arise in case of a "perfect" east oder west profile. Then the slope would be ∞ or -∞ and therefore simply NA. 

```
a <- rep(1, 10)
b <- 1:10

lm(b ~ a)
```

To prevent this (admittedly improbable) error, you could catch it and set the slope manually to a very high or very low number (or do something even more sophisticated). 

```
tryCatch(
  lm(b~a, singular.ok = F),
  error = function(e) {
    print(e)
    slope <- 513
    # TODO: something cooler
  }
)
```

**Comment by MoritzMennenga** [comment] 2017-08-11 09:07
thanks for your thoughts!! The first solution is the way I did it in anonther step…. Don’t know why not here.
It is an admittedly improbable error, but I got it with real world data from an excavation.
I will change the code and try to fix the error

**Comment by MoritzMennenga** [comment] 2017-08-11 15:09
I fixed it now without errorhandling

**Comment by MoritzMennenga** [comment] 2017-08-29 08:56
I did a check of accuracy with the last Version in QGIS, the results are fine (projected and horizontal):
I have a grid of 10.2 x 10.2 cm (1m x 0,7m) with 5 fg points.
Photo 1: Profile 0° (vertical), Camera 20°, 
distance y calculated = 10.2 cm, distance measured = 10.2 cm
distance x calculated = 10.2 cm, distance measured = 10.2 cm
Photo 2: Profile 12°, Camera 20°
distance y calculated = 9.977 cm, distance measured = 9.95 cm
distance x calculated = 10.2 cm, distance measured = 10.2 cm
Photo 3: Profile 20°, Camera 20°
distance y calculated = 9.585 cm, distance measured = 9.6 cm
distance x calculated = 10.2 cm, distance measured = 10.2 cm

In the surface mode all distances have to be 10.2 cm all the time -> this works perfectly, too!

**Closed as completed** 2020-07-10 07:37 UTC
Labels: profileAAR
